import { describe, it, expect, beforeAll, vi } from 'vitest';
import request from 'supertest';
import jwt from 'jsonwebtoken';

// Mock @digitalchokro/askchokro before importing createApp
const mockAsk = vi.fn();
const mockPing = vi.fn();
const mockDispose = vi.fn();

vi.mock('@digitalchokro/askchokro', () => ({
  AskChokro: vi.fn(function MockAskChokro() {
    return {
      ask: mockAsk,
      ping: mockPing,
      dispose: mockDispose,
      annotate: vi.fn(),
    };
  }),
}));

vi.mock('@digitalchokro/adapter-express', () => ({
  createAskChokroMiddleware: vi.fn(() => async (req: any, res: any) => {
    try {
      const result = await mockAsk(req.body.question, req.body.context ?? {});
      res.status(200).json(result);
    } catch (err: any) {
      res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: err.message } });
    }
  }),
  createAskChokroStreamMiddleware: vi.fn(() => async (req: any, res: any) => {
    // simplified mock: just return JSON
    try {
      const result = await mockAsk(req.body.question, req.body.context ?? {});
      res.status(200).json(result);
    } catch (err: any) {
      res.status(500).json({ error: { code: 'INTERNAL_ERROR', message: err.message } });
    }
  }),
}));

vi.mock('dotenv/config', () => ({}));

describe('@digitalchokro/microservice', () => {
  const JWT_SECRET = 'test-secret-key';

  describe('/health endpoint', () => {
    it('returns 200 with connected status when ping() succeeds', async () => {
      mockPing.mockResolvedValue(true);
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      const res = await request(app).get('/health');
      expect(res.status).toBe(200);
      expect(res.body).toMatchObject({
        status: 'ok',
        engine: 'AskChokro Microservice',
        database: 'connected',
      });
    });

    it('returns 503 with disconnected status when ping() fails', async () => {
      mockPing.mockResolvedValue(false);
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      const res = await request(app).get('/health');
      expect(res.status).toBe(503);
      expect(res.body).toMatchObject({
        status: 'error',
        database: 'disconnected',
      });
    });
  });

  describe('/api/ask authentication', () => {
    beforeAll(() => {
      vi.clearAllMocks();
      mockPing.mockResolvedValue(true);
    });

    it('returns 401 if no Authorization header is sent', async () => {
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      const res = await request(app)
        .post('/api/ask')
        .send({ question: 'test' });

      expect(res.status).toBe(401);
      expect(res.body.error).toMatch(/Unauthorized/);
    });

    it('returns 401 if token is invalid', async () => {
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      const res = await request(app)
        .post('/api/ask')
        .set('Authorization', 'Bearer invalid.token.here')
        .send({ question: 'test' });

      expect(res.status).toBe(401);
    });

    it('passes through if no JWT_SECRET is configured (open mode)', async () => {
      mockAsk.mockResolvedValue({ answer: 'Open mode result' });
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: undefined }); // no secret = open mode

      const res = await request(app)
        .post('/api/ask')
        .send({ question: 'What is the revenue?' });

      expect(res.status).toBe(200);
      expect(res.body.answer).toBe('Open mode result');
    });

    it('accepts a valid JWT and forwards request to the agent', async () => {
      mockAsk.mockResolvedValue({ answer: 'Total revenue is $5000' });
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      const token = jwt.sign({ wp_user_id: '42', sub: 'user-42' }, JWT_SECRET);

      const res = await request(app)
        .post('/api/ask')
        .set('Authorization', `Bearer ${token}`)
        .send({ question: 'What is the revenue?' });

      expect(res.status).toBe(200);
      expect(res.body.answer).toBe('Total revenue is $5000');
    });

    it('maps vendor_id from JWT to tenantId in context (Dokan / WCFM support)', async () => {
      mockAsk.mockResolvedValue({ answer: 'Vendor revenue is $1200' });
      const { createApp } = await import('../index.js');
      const { app } = createApp({ jwtSecret: JWT_SECRET });

      // Simulate a JWT generated by the WP plugin containing vendor_id
      const token = jwt.sign({ user_id: '7', vendor_id: '42', sub: 'vendor-42' }, JWT_SECRET);

      const res = await request(app)
        .post('/api/ask')
        .set('Authorization', `Bearer ${token}`)
        .send({ question: 'What is my revenue?' });

      expect(res.status).toBe(200);
      // The context passed to mockAsk should have tenantId = '42' (strings because JWT claims are strings)
      expect(mockAsk).toHaveBeenLastCalledWith(
        'What is my revenue?',
        expect.objectContaining({ tenantId: '42', vendor_id: '42', user_id: '7' })
      );
    });
  });

  describe('Tenant Scoping Configuration', () => {
    it('initializes AskChokro with tenantScoping enabled when flag is set', async () => {
      const { AskChokro } = await import('@digitalchokro/askchokro');
      vi.clearAllMocks();
      mockPing.mockResolvedValue(true);

      const { createApp } = await import('../index.js');
      createApp({ jwtSecret: JWT_SECRET, enableTenantScoping: true, tenantColumn: 'vendor_id' });

      expect(AskChokro).toHaveBeenCalledWith(
        expect.objectContaining({
          options: expect.objectContaining({
            tenantScoping: expect.objectContaining({
              enabled: true,
              column: 'vendor_id',
            }),
          }),
        })
      );
    });

    it('initializes AskChokro without tenantScoping when disabled', async () => {
      const { AskChokro } = await import('@digitalchokro/askchokro');
      vi.clearAllMocks();

      const { createApp } = await import('../index.js');
      createApp({ jwtSecret: JWT_SECRET, enableTenantScoping: false });

      expect(AskChokro).toHaveBeenCalledWith(
        expect.objectContaining({
          options: expect.objectContaining({
            tenantScoping: undefined,
          }),
        })
      );
    });
  });
});
