/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-return, @typescript-eslint/unbound-method, @typescript-eslint/explicit-function-return-type, @typescript-eslint/no-unnecessary-type-assertion */
import { describe, it, expect } from 'vitest';
import { DefaultSQLValidator } from '../../pipeline/sql-validator.js';

/**
 * Security test suite — validates that the SQL validator correctly
 * blocks dangerous queries that could be generated by a misbehaving LLM.
 */

const validator = new DefaultSQLValidator();
const dialect = 'postgresql';

describe('SQL Injection Prevention', () => {
  it('blocks DROP TABLE statements', () => {
    const result = validator.validate('DROP TABLE users', dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks DELETE statements', () => {
    const result = validator.validate('DELETE FROM users WHERE id = 1', dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks INSERT statements', () => {
    const result = validator.validate("INSERT INTO users (name) VALUES ('evil')", dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks UPDATE statements', () => {
    const result = validator.validate("UPDATE users SET name = 'hacked' WHERE id = 1", dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks TRUNCATE statements', () => {
    const result = validator.validate('TRUNCATE TABLE users', dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks ALTER TABLE statements', () => {
    const result = validator.validate('ALTER TABLE users ADD COLUMN evil TEXT', dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks GRANT statements', () => {
    const result = validator.validate('GRANT ALL ON users TO public', dialect);
    expect(result.valid).toBe(false);
  });

  it('blocks multi-statement injection (SELECT + DROP)', () => {
    const result = validator.validate('SELECT 1; DROP TABLE users;', dialect);
    expect(result.valid).toBe(false);
  });

  it('allows valid SELECT queries', () => {
    const result = validator.validate('SELECT id, name FROM users WHERE id = 1', dialect);
    expect(result.valid).toBe(true);
  });

  it('allows SELECT with JOINs', () => {
    const result = validator.validate(
      'SELECT u.name, o.total_amount FROM users u JOIN orders o ON u.id = o.user_id',
      dialect,
    );
    expect(result.valid).toBe(true);
  });

  it('allows SELECT with aggregations', () => {
    const result = validator.validate(
      'SELECT COUNT(*) as total, AVG(price) as avg_price FROM products GROUP BY category',
      dialect,
    );
    expect(result.valid).toBe(true);
  });

  it('blocks queries referencing blocked tables when configured', () => {
    const result = validator.validate(
      'SELECT * FROM admin_secrets',
      dialect,
      undefined,
      ['admin_secrets'],
    );
    expect(result.valid).toBe(false);
  });

  it('blocks queries referencing blocked columns when configured', () => {
    const result = validator.validate(
      'SELECT password_hash FROM users',
      dialect,
      undefined,
      undefined,
      ['password_hash'],
    );
    expect(result.valid).toBe(false);
  });
});
